package invoice

var pdfHead = []string{
	"MatchX GmbH",
	"Brückenstraße 4",
	"10179 Berlin",
	"Germany",
	"Tax number: 37/436/50071",
	"awesome@matchx.io",
	"VAT ID: DE309834893",
	"INVOICE NUMBER MUST BE INCLUDED WITH YOUR BANK PAYMENT OTHERWISE DELAYS",
	"MAY OCCUR",
	"1 of 1",
}
var pdfPaymentInfo = []string{
	"Payment details:",
	"Payment must be made within 30 days from issue date.",
	"BIC: PBNKDEFF",
	"IBAN: DE12 1001 0010 0685 1601 27",
	"BANK: Post Bank",
	"ACCOUNT HOLDER: MatchX GmbH",
	"PayPal: info@matchx.io",
}

var vatMap = map[string]*vat{
	"US":             {dateReachLimit: "", rateUnderLimit: 0, rateOverLimit: 0},
	"Germany":        {dateReachLimit: "", rateUnderLimit: 0.19, rateOverLimit: 0.19},
	"Netherlands":    {dateReachLimit: "14.01.2021", rateUnderLimit: 0.19, rateOverLimit: 0.21},
	"Austria":        {dateReachLimit: "10.05.2021", rateUnderLimit: 0.19, rateOverLimit: 0.20},
	"Belgium":        {dateReachLimit: "08.03.2021", rateUnderLimit: 0.19, rateOverLimit: 0.21},
	"Bulgaria":       {dateReachLimit: "", rateUnderLimit: 0.19, rateOverLimit: 0.20},
	"Croatia":        {dateReachLimit: "23.09.2021", rateUnderLimit: 0.19, rateOverLimit: 0.25},
	"Cyprus":         {dateReachLimit: "10.06.2021", rateUnderLimit: 0.19, rateOverLimit: 0.19},
	"Czech Republic": {dateReachLimit: "11.04.2021", rateUnderLimit: 0.19, rateOverLimit: 0.21},
	"Denmark":        {dateReachLimit: "15.05.2021", rateUnderLimit: 0.19, rateOverLimit: 0.25},
	"Estonia":        {dateReachLimit: "", rateUnderLimit: 0.19, rateOverLimit: 0.20},
	"Finland":        {dateReachLimit: "21.08.2021", rateUnderLimit: 0.19, rateOverLimit: 0.24},
	"France":         {dateReachLimit: "19.03.2021", rateUnderLimit: 0.19, rateOverLimit: 0.20},
	"Greece":         {dateReachLimit: "01.06.2021", rateUnderLimit: 0.19, rateOverLimit: 0.24},
	"Hungary":        {dateReachLimit: "06.10.2021", rateUnderLimit: 0.19, rateOverLimit: 0.27},
	"Ireland":        {dateReachLimit: "29.04.2021", rateUnderLimit: 0.19, rateOverLimit: 0.23},
	"Italy":          {dateReachLimit: "09.04.2021", rateUnderLimit: 0.19, rateOverLimit: 0.22},
	"Latvia":         {dateReachLimit: "05.10.2021", rateUnderLimit: 0.19, rateOverLimit: 0.21},
	"Lithuania":      {dateReachLimit: "", rateUnderLimit: 0.19, rateOverLimit: 0.21},
	"Luxembourg":     {dateReachLimit: "", rateUnderLimit: 0.19, rateOverLimit: 0.17},
	"Malta":          {dateReachLimit: "", rateUnderLimit: 0.19, rateOverLimit: 0.18},
	"Monaco":         {dateReachLimit: "", rateUnderLimit: 0.19, rateOverLimit: 0.20},
	"Poland":         {dateReachLimit: "04.05.2021", rateUnderLimit: 0.19, rateOverLimit: 0.23},
	"Portugal":       {dateReachLimit: "28.04.2021", rateUnderLimit: 0.19, rateOverLimit: 0.23},
	"Romania":        {dateReachLimit: "23.04.2021", rateUnderLimit: 0.19, rateOverLimit: 0.19},
	"Slovakia":       {dateReachLimit: "17.04.2021", rateUnderLimit: 0.19, rateOverLimit: 0.20},
	"Slovenia":       {dateReachLimit: "25.09.2021", rateUnderLimit: 0.19, rateOverLimit: 0.22},
	"Spain":          {dateReachLimit: "24.04.2021", rateUnderLimit: 0.19, rateOverLimit: 0.21},
	"Sweden":         {dateReachLimit: "06.05.2021", rateUnderLimit: 0.19, rateOverLimit: 0.25},
	"UK":             {dateReachLimit: "", rateUnderLimit: 0, rateOverLimit: 0},
	"South Korea":    {dateReachLimit: "", rateUnderLimit: 0, rateOverLimit: 0},
}
var vatCountryCode = map[string]string{
	"DE": "Germany",
	"NL": "Netherlands",
	"AT": "Austria",
	"BE": "Belgium",
	"BG": "Bulgaria",
	"HR": "Croatia",
	"CY": "Cyprus",
	"CZ": "Czech Republic",
	"DK": "Denmark",
	"EE": "Estonia",
	"FI": "Finland",
	"FR": "France",
	"EL": "Greece",
	"HU": "Hungary",
	"IE": "Ireland",
	"IT": "Italy",
	"LV": "Latvia",
	"LT": "Lithuania",
	"LU": "Luxembourg",
	"MT": "Malta",
	"PL": "Poland",
	"PT": "Portugal",
	"RO": "Romania",
	"SK": "Slovakia",
	"SI": "Slovenia",
	"ES": "Spain",
	"SE": "Sweden",
	"GB": "UK",
	"XI": "UK",
}

var dateLayout1 = "March 1, 2021"
var dateLayout2 = "14.02.2021"
var month = map[string]int{
	"January":   1,
	"February":  2,
	"March":     3,
	"April":     4,
	"May":       5,
	"June":      6,
	"July":      7,
	"August":    8,
	"September": 9,
	"October":   10,
	"November":  11,
	"December":  12,
}
